samples_file: config/samples.yaml

reference_fasta: reference/hs1.fa
bwa_index: reference/hs1.fa

trim: true
trim_adapters:
  # Fallback adapters used only if guessadapt does not return a usable sequence.
  read1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  read2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
trim_quality_cutoff: 20
minimum_trimmed_length: 30

threads:
  index: 4
  trim: 4
  map: 8
  sort: 4
  index_bam: 2

resources:
  index:
    mem_mb: 4000
    runtime: 60
  trim:
    mem_mb: 4000
    runtime: 60
  guess_adapters:
    mem_mb: 2000
    runtime: 15
  map:
    mem_mb: 16000
    runtime: 240
  sort:
    mem_mb: 8000
    runtime: 120
  index_bam:
    mem_mb: 2000
    runtime: 30

sort_memory_per_thread: 1G

read_group:
  platform: ILLUMINA
  library: default_library
  platform_unit: default_unit
